package ru.chislab.fireSystemTester.enums;

public enum ZoneTypes {

    EMPTY_TYPE,
    SIGNAL_LINE_STATE,
    CONTROL_CIRCUITS_STATE,
    DEVICE_STATE,
    ON_OFF_AUTOMATICS,
    START_RESET_OR_REMOTE_START,
    NUMBER_VALUE,
    IMPULSE_COUNTER,
    BACKUP_POWER_SUPPLY
}
